<?php
	require_once get_template_directory() . '/lib/metaboxes/page.php';
	require_once get_template_directory() . '/lib/metaboxes/features.php';
	require_once get_template_directory() . '/lib/metaboxes/glossary.php';
	require_once get_template_directory() . '/lib/metaboxes/people.php';
	require_once get_template_directory() . '/lib/metaboxes/success-stories.php';
	require_once get_template_directory() . '/lib/metaboxes/testimonials.php';
	require_once get_template_directory() . '/lib/metaboxes/integrations.php';
	require_once get_template_directory() . '/lib/metaboxes/awards.php';
	require_once get_template_directory() . '/lib/metaboxes/academy.php';
	require_once get_template_directory() . '/lib/metaboxes/templates.php';
	require_once get_template_directory() . '/lib/metaboxes/directory.php';
	require_once get_template_directory() . '/lib/metaboxes/sidebar-show-h3.php';
	require_once get_template_directory() . '/lib/metaboxes/signup-sidebar.php';
	require_once get_template_directory() . '/lib/metaboxes/cta-button.php';
	require_once get_template_directory() . '/lib/metaboxes/custom-urls.php';
	require_once get_template_directory() . '/lib/metaboxes/checklists.php';
	require_once get_template_directory() . '/lib/metaboxes/reviews.php';
	require_once get_template_directory() . '/lib/metaboxes/videos.php';
	require_once get_template_directory() . '/lib/metaboxes/landing-ppc.php';
  // require_once get_template_directory() . '/lib/metaboxes/webinars.php';
