<?php
	require_once get_template_directory() . '/lib/post-types/academy.php';
	require_once get_template_directory() . '/lib/post-types/features.php';
	require_once get_template_directory() . '/lib/post-types/glossary.php';
	require_once get_template_directory() . '/lib/post-types/integrations.php';
	require_once get_template_directory() . '/lib/post-types/people.php';
	require_once get_template_directory() . '/lib/post-types/success-stories.php';
	require_once get_template_directory() . '/lib/post-types/testimonials.php';
	require_once get_template_directory() . '/lib/post-types/clients.php';
	require_once get_template_directory() . '/lib/post-types/awards.php';
	require_once get_template_directory() . '/lib/post-types/alternatives.php';
	require_once get_template_directory() . '/lib/post-types/templates.php';
	require_once get_template_directory() . '/lib/post-types/directory.php';
	require_once get_template_directory() . '/lib/post-types/about.php';
	require_once get_template_directory() . '/lib/post-types/research.php';
	require_once get_template_directory() . '/lib/post-types/checklists.php';
	require_once get_template_directory() . '/lib/post-types/reviews.php';
	require_once get_template_directory() . '/lib/post-types/videos.php';
	require_once get_template_directory() . '/lib/post-types/pricing-tables.php';
	require_once get_template_directory() . '/lib/post-types/landing-ppc.php';
	// require_once get_template_directory() . '/lib/post-types/webinars.php';
