<?php

$metabox = array(
	'id'         => 'mb_directory',
	'capability' => 'edit_posts',
	'name'       => 'Directory',
	'post_type'  => array( 'ms_directory' ),
	'priority'   => 'high',
	'args'       => array(
		array(
			'id'          => 'mb_directory_website',
			'label'       => 'Website URL',
			'description' => '',
			'type'        => 'text',
		),
		array(
			'id'          => 'mb_directory_support-portal',
			'label'       => 'Support Portal URL',
			'description' => '',
			'type'        => 'text',
		),
		array(
			'id'          => 'mb_directory_business-hours',
			'label'       => 'Business Hours',
			'description' => '',
			'type'        => 'editor',
		),
		array(
			'id'          => 'mb_directory_address',
			'label'       => 'Address',
			'description' => '',
			'type'        => 'editor',
		),
		array(
			'id'          => 'mb_directory_email-support',
			'label'       => 'Email Support (email)',
			'description' => '',
			'type'        => 'text',
		),
		array(
			'id'          => 'mb_directory_livechat-support',
			'label'       => 'Live Chat Support URL',
			'description' => '',
			'type'        => 'text',
		),
		array(
			'id'          => 'mb_directory_call-center-support',
			'label'       => 'Call Center Support (tel. number)',
			'description' => '',
			'type'        => 'text',
		),
		array(
			'id'          => 'mb_directory_knowledge-base',
			'label'       => 'Knowledge Base URL',
			'description' => '',
			'type'        => 'text',
		),
		array(
			'id'          => 'mb_directory_forum',
			'label'       => 'Forum URL',
			'description' => '',
			'type'        => 'text',
		),
		array(
			'id'          => 'mb_directory_instagram',
			'label'       => 'Instagram URL',
			'description' => '',
			'type'        => 'text',
		),
		array(
			'id'          => 'mb_directory_facebook',
			'label'       => 'Facebook URL',
			'description' => '',
			'type'        => 'text',
		),
		array(
			'id'          => 'mb_directory_twitter',
			'label'       => 'Twitter URL',
			'description' => '',
			'type'        => 'text',
		),
		array(
			'id'          => 'mb_directory_wikipedia',
			'label'       => 'Wikipedia URL',
			'description' => '',
			'type'        => 'text',
		),
		array(
			'id'          => 'mb_directory_email-sla',
			'label'       => 'Email SLA',
			'description' => '',
			'type'        => 'select',
			'args'        => array(
				'N/A'        => 'na',
				'15 Minutes' => '15min',
				'30 Minutes' => '30min',
				'1 Hour'     => '1h',
				'6 Hours'    => '6h',
				'12 Hour'    => '12h',
				'1 Day'      => '1d',
				'2 Days'     => '2d',
				'3 Days'     => '3d',
				'1 Week'     => '1w',
				'1 Month'    => '1mo',
			),
		),
		array(
			'id'          => 'mb_directory_livechat-sla',
			'label'       => 'Live Chat SLA',
			'description' => '',
			'type'        => 'select',
			'args'        => array(
				'N/A'        => 'na',
				'15 Minutes' => '15min',
				'30 Minutes' => '30min',
				'1 Hour'     => '1h',
				'6 Hours'    => '6h',
				'12 Hour'    => '12h',
				'1 Day'      => '1d',
				'2 Days'     => '2d',
				'3 Days'     => '3d',
				'1 Week'     => '1w',
				'1 Month'    => '1mo',
			),
		),
		array(
			'id'          => 'mb_directory_call-center-sla',
			'label'       => 'Call Center SLA',
			'description' => '',
			'type'        => 'select',
			'args'        => array(
				'N/A'        => 'na',
				'15 Minutes' => '15min',
				'30 Minutes' => '30min',
				'1 Hour'     => '1h',
				'6 Hours'    => '6h',
				'12 Hour'    => '12h',
				'1 Day'      => '1d',
				'2 Days'     => '2d',
				'3 Days'     => '3d',
				'1 Week'     => '1w',
				'1 Month'    => '1mo',
			),
		),
		array(
			'id'          => 'mb_directory_forum-sla',
			'label'       => 'Forum SLA',
			'description' => '',
			'type'        => 'select',
			'args'        => array(
				'N/A'        => 'na',
				'15 Minutes' => '15min',
				'30 Minutes' => '30min',
				'1 Hour'     => '1h',
				'6 Hours'    => '6h',
				'12 Hour'    => '12h',
				'1 Day'      => '1d',
				'2 Days'     => '2d',
				'3 Days'     => '3d',
				'1 Week'     => '1w',
				'1 Month'    => '1mo',
			),
		),
		array(
			'id'          => 'mb_directory_industry',
			'label'       => 'Industry',
			'description' => '',
			'type'        => 'select',
			'args'        => array(
				'Accounting & Legal'     => 'accounting-legal',
				'Automotive'             => 'automotive',
				'Banking & Insurance'    => 'banking-insurance',
				'E-commerce & Services'  => 'e-commerce-services',
				'Entertainment'          => 'entertainment',
				'eSports'                => 'esports',
				'Fashion'                => 'fashion',
				'Healthcare'             => 'healthcare',
				'HR & Recruitment'       => 'hr-recruitment',
				'Marketing & TelCo'      => 'marketing-telecommunications',
				'Real Estate'            => 'construction-real-estate',
				'Retail'                 => 'retail',
				'SaaS'                   => 'saas',
				'Software & Internet'    => 'software-internet',
				'Travel & Accommodation' => 'travel-accommodation',
				'Webhosting'             => 'webhosting',
			),
		),
		array(
			'id'          => 'mb_directory_business',
			'label'       => 'Business',
			'description' => '',
			'type'        => 'select',
			'args'        => array(
				'Agency'            => 'agency',
				'EDU and NGOs'      => 'education-ngo',
				'Enterprise'        => 'enterprise',
				'Government'        => 'government',
				'Solopreneur'       => 'solo',
				'Startups and SMBs' => 'startups',
			),
		),
		array(
			'id'          => 'mb_directory_location',
			'label'       => 'Location',
			'description' => '<em>Google Maps Embed</em>',
			'type'        => 'textarea',
		),
		array(
			'id'          => 'mb_directory_company-name',
			'label'       => 'Company Name',
			'description' => '',
			'type'        => 'text',
		),
		array(
			'id'          => 'mb_directory_terms-conditions',
			'label'       => 'Terms & Conditions',
			'description' => '',
			'type'        => 'text',
		),
		array(
			'id'          => 'mb_directory_privacy-policy',
			'label'       => 'Privacy Policy',
			'description' => '',
			'type'        => 'text',
		),
		array(
			'id'          => 'mb_directory_security-policy',
			'label'       => 'Security Policy',
			'description' => '',
			'type'        => 'text',
		),
		array(
			'id'          => 'mb_directory_gdpr',
			'label'       => 'GDPR',
			'description' => '',
			'type'        => 'text',
		),
		array(
			'id'          => 'mb_directory_affiliate-program',
			'label'       => 'Affiliate Program',
			'description' => '',
			'type'        => 'text',
		),
		array(
			'id'          => 'mb_directory_faq-text',
			'label'       => 'FAQ - Subheadline',
			'description' => '',
			'type'        => 'text',
		),
	),
);

new trueMetaBox( $metabox );
