name: Build Test - QU HowTos

on:
  pull_request:
    paths:
      - 'lib/widgets/qu-howtos/**/*'
  push:
    paths:
      - 'lib/widgets/qu-howtos/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib/widgets/qu-howtos/
    strategy:
      matrix:
        node_version: [ '16' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Yarn dependencies
        run: yarn

      - name: Run tests
        run: yarn build
