name: Build Test - QU Checklists

on:
  pull_request:
    paths:
      - 'lib/widgets/qu-checklists/**/*'
  push:
    paths:
      - 'lib/widgets/qu-checklists/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib/widgets/qu-checklists/
    strategy:
      matrix:
        node_version: [ '14', '16' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Yarn dependencies
        run: yarn

      - name: Run tests
        run: yarn build
