name: Build Test - Web Calc Featured

on:
  pull_request:
    paths:
      - 'apps/web-calc-featured/**/*'
  push:
    paths:
      - 'apps/web-calc-featured/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/web-calc-featured/
    strategy:
      matrix:
        node_version: [ '14', '16' ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Yarn dependencies
        run: yarn

      - name: Run tests
        run: yarn build
