name: Deployment

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      version:
        required: true
        type: string
      shasum:
        required: true
        type: string
    secrets:
      CICD_USER_PAT:
        required: true

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - name: Trigger downstream pipeline
        id: trigger
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: update.yml
          repo: QualityUnit/liveagent-wp
          ref: dev
          token: ${{ secrets.CICD_USER_PAT }}
          wait-for-completion-interval: 5s
          inputs: '{
                  "repository":"${{ inputs.repository }}",
                  "version":"${{ inputs.version }}",
                  "shasum":"${{ inputs.shasum }}"
                }'
