name: Release Nightly

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-nightly'

jobs:
  build:
    name: 1️⃣ Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: 'yarn'

      - name: Install Composer Dependencies
        run: composer install

      - name: Build All CSS and JS
        run: yarn build:all

      - name: Remove Unnecessary Files [theme]
        run: rm -rf node_modules vendor .git .idea .github .husky *.md *.lock .editorconfig .eslintignore .eslintrc .gitignore .stylelintrc composer.json gulpfile.js commitlint.config.js package.json phpcs.xml

      - name: Remove Unnecessary Files [web-calc]
        working-directory: ./apps/web-calc/
        run: rm -rf node_modules public src build.js package.json README.md yarn.lock

      - name: Remove Unnecessary Files [web-calc-featured]
        working-directory: ./apps/web-calc-featured/
        run: rm -rf node_modules public src build.js package.json README.md yarn.lock

      - name: Remove Unnecessary Files [typing-test]
        working-directory: ./apps/typing-test/
        run: rm -rf node_modules public src .babelrc package.json README.md tsconfig.json webpack.config.js yarn.lock

      - name: Remove Unnecessary Files [qu-checklists]
        working-directory: ./lib/widgets/qu-checklists/
        run: rm -rf node_modules package.json yarn.lock webpack.config.js

      - name: Remove Unnecessary Files [qu-howtos]
        working-directory: ./lib/widgets/qu-howtos/
        run: rm -rf node_modules package.json yarn.lock webpack.config.js

      - name: Remove Unnecessary Files [qu-expertnote]
        working-directory: ./lib/widgets/qu-expertnote/
        run: rm -rf node_modules package.json yarn.lock webpack.config.js

      - name: Remove Unnecessary Files [qu-usecase]
        working-directory: ./lib/widgets/qu-usecase/
        run: rm -rf node_modules package.json yarn.lock webpack.config.js

      - name: Remove Unnecessary Files [statistics]
        working-directory: ./lib/widgets/statistics/
        run: rm -rf node_modules package.json yarn.lock

      - name: Get the Version
        id: version
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref }}
          regex: ".*/([^/]+)$"

      - name: Create a ZIP File
        run: zip -r liveagent_${{ steps.version.outputs.group1 }}.zip .

      - name: Create a Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: changelog

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: true
          body: |
            ${{ steps.changelog.outputs.changelog }}
          generate_release_notes: true
          append_body: true
          files: ./liveagent_${{ steps.version.outputs.group1 }}.zip
